### ISSUE TITLE
Doporučování pluginů

### ISSUE THREAD

**Issue by kalich5** [skaut/dsw-oddil#116]
Your theme recommends 2 plugins. Could you please explain the reason for their requirement?

**Comment by kalich5** [comment]
Tady bych to asi klidně omezil jen na ten image widget. A nebo bych je úplně vyhodil a řešil to přes ten plugin co bude dělat nastavení

**Comment by literat** [comment]
Duplikuje #87 (Kalichu nauč se číst). Zavírám.
