### ISSUE TITLE
Jak nás probírají na Slacku

### ISSUE THREAD

**Issue by kalich5** [skaut/dsw-oddil#118]
rmdiaconu [11:49 AM] Star this message
is it allowed to ask for more time to fix the bugs over and over again?

[11:50] 
one of the authors of a theme I’m reviewing asked for the 3rd time in a row for 2 weeks to upload a new version

**Comment by kalich5** [comment]
kenshino [11:53 AM] 
Yup. It would be terrible to close it because of a technicality and make them wait another 4 months :slightly_smiling_face:

[11:53] Star this message
Use your discretion to help fellow developers :))

**Comment by kalich5** [comment]
rmdiaconu [11:54 AM] Star this message
I’m trying

[11:54] Star this message
but after 7 days from the review I ask if there is a new version

[11:54] 
and I get the request to give them 2 weeks

[11:54] Star this message
So that’s 3 weeks

[11:54] Star this message
and when a new version is uploaded, very little has changed

[11:54] Star this message
that’s why I am asking

**Comment by kalich5** [comment]
kenshino [11:55 AM] Star this message
Ticket no? :slightly_smiling_face:

**Comment by kalich5** [comment]
rmdiaconu [11:56 AM] Star this message
29097

**Comment by kalich5** [comment]
kenshino [12:10 PM] Star this message
I'm looking into that user

**Comment by literat** [comment]
Neřeší žádný problém v rámci šablony. Zavírám.
