### ISSUE TITLE
Automatická aktualizace šablony

### ISSUE THREAD

**Issue by literat** [skaut/dsw-oddil#122]
Umožnit automatickou aktualizaci šablony dsw z vlasního zdroje; tj buď z dobryweb.skauting.cz anebo využít jiný prostředek.

**Comment by literat** [comment]
Dohoda o použití Github Releases:

1.	DSW se standardně vyvíjí
2.	Až se dojde k závěru, že máme smysluplnou novou verzi, vyrobí se tag
3.	Autor tagu šablonu zbuildí a vytvoří nový release podle tagu, ke kterému zabalenou šablonu připravenou k distribuci přidá jako asset. Zároveň tam vyplní úryvek z changelogu
4.	Klientské WP začnou novou verzi stahovat a instalovat

https://help.github.com/articles/creating-releases/
https://developer.github.com/v3/repos/releases/#get-the-latest-release

**Comment by vojta001** [comment]
Teoreticky to takhle funguje, problém je pouze při zjišťování aktuální verze šablony. Tu si WP (pro mě celkem nepochopitelně) bere z CSS, [kde](https://github.com/skaut/dsw-oddil/blob/3bbc963ca5d851eedc0c5fb8ea7a5ebf7901cb8d/style.css#L7) je nahardcorovaná 1.0, což script vyhodnotí jako nejnovější a aktualizaci nenabídne. Nejjednodušším řešením je asi vždy při vydání nové verze ji zapsat i do CSS

**Comment by literat** [comment]
Wordpress pro to má celkem pochopitelné důvody. Z hlavičky css souboru bere základní informace o šabloně, které pak zobrazuje (https://codex.wordpress.org/Theme_Development). Čili i onu verzi. Je to prostě respektovaný standard.

Jako řešení bych tedy viděl upravit Gruntfile.js, aby při buildu updatoval i verzi v tomto souboru. V podstatě by to měl být jednoduchý sed; node na to bude mít určitě nějakou chytristiku.

**Comment by vojta001** [comment]
Zkusím tedy něco [takového](https://stackoverflow.com/questions/20020981/grunt-how-to-replace-paths-in-html-file-using-grunt-task)

**Comment by kalich5** [comment]
Já bych teď v číslování vycházel z toho, jak značíme verze. Takže třeba 0.20.0 atd.

Až bude šablona hotová a budeme přecházet na WordPress org, tak bych přešel na verzi 1.0 aby to bylo jasně oddělené.

**Comment by literat** [comment]
@vojta001 V podstatě asi nějak tak.

@kalich5 Číslování zatím prosím neřeš. Nejdříve to potřebujeme technicky rozeběhnout. Takže @vojta001 si tam nyní použije takovou verzi, jakou bude potřebovat. Až do bude fungovat, tak teprve doladíme číslování.

**Comment by vojta001** [comment]
Mě verze moc nezajímá, já použiju tu z `Gruntfile.js`, takže číslování žádným způsobem neovlivním.

@kalich5 O 1.0 jsem psal jen proto, že je v tuto chvíli uvedená v CSS, takže ačkoli můj kód funguje, není to vidět, protože když porovná 1.0 s verzí z GitHubu (0.16.1), dojde k závěru, že update není potřeba.

**Comment by vojta001** [comment]
Mám problém obecně s `grunt build`. Chyba nastane při LESS kompilaci `src/main.less`.
Problém je v `@import "components/bootstrap/less/variables";` a ani já netuším, kde by ten soubor měl být

**Comment by literat** [comment]
Komponenty nainstaluješ pomocí boweru, dle bower.json. Tam jsou definované závislosti. Jasně, je to už trošku starší řešení...

**Comment by vojta001** [comment]
Ještě drobná chybka, ladil jsem to podle master branche

**Comment by vojta001** [comment]
Tak snad je to hotové, Grunt mi dal pěkně zabrat
