### ISSUE TITLE
Použít písmo TheMixCE

### ISSUE THREAD

**Issue by literat** [skaut/dsw-oddil#22]
_From @literat on July 17, 2014 10:51_

Přeformátovat písmo TheMixCE pro použití na webu a vložit do stránky.

_Copied from original issue: literat/dsw-oddil-wp-theme#3_

**Comment by literat** [comment]
branch: feature-3-use-themixce-font

Nastaveno použití písma The Mix CE.

DONE!

**Comment by peci1** [comment]
Ve Firefoxu a IE to pismo vypada dost odporne (pouziva woff verzi). Pismo je desne kostrbate.

![ff](https://cloud.githubusercontent.com/assets/182533/11520497/422a8b0c-98a4-11e5-9e54-aeaa644f8df0.jpg)

![chrome](https://cloud.githubusercontent.com/assets/182533/11520500/45a26de0-98a4-11e5-87f8-1076d2da25cd.jpg)

**Comment by literat** [comment]
Jakou používáte prosím verzi jednotlivých prohlížečů a jaké máte rozlišení displaye?

**Comment by peci1** [comment]
Vsechny v aktualni stable verzi. FF 32bit, zbytek 64bit. Windows 7 64bit. Zitra vyzkousim pod Ubuntu. Rozliseni FullHD se zapnutym systemovym zvetsenim na 125% (takze devicePixelRatio 1.25).

**Comment by peci1** [comment]
Hmm, tak na Linuxu se to zobrazuje ve vsech prohlizecich dobre. Mozna to bude problem vznikly z toho, ze TheMixCE mam na Windows nainstalovane v systemu a ve Wordu apod. vypada taky osklive. Ale Firefox mi tvrdil, ze pouziva TheMixCE stazeny z woff souboru, a nikoli ten lokalni. Tohle pismo proste potrebuje antialiasing, a mozna ho proste nektere programy delaji a jine ne.

**Comment by literat** [comment]
Tak jsem to zkoušel na čem jsem mohl a co jsem sehnal. Jak píšeš, tak unix like systémy jsou v pohodě. Žádný problém na Linuxu ani Macu. Na Windows jak který problížeč a jak která verze. IE 11 je v pohodě. S novým Edge už je to horší. Aktuální FF také spáše horší zkušenost. Chrome naopak v pohodě. Písmo mám také lokálně, nicméně všechny prohlížeče používají právě to woffko. S bratrem Ňufem jsem to vyhodnotili jako špatný systémový antialiasing.

Písmo není zrovna webové a vychází ze současného grafického manuálu Junáka. Font byl generovaný pomocí http://www.fontsquirrel.com/tools/webfont-generator. Zkoušel jsem ho několikrát vygenerovat znovu s většinou ne moc odlišným výsledkem.

Máš-li zkušenosti s jinými generátory, tak můžeme vyzkoušet i něco jiného, jestli to povede ke zlepšení nebo budou všechny výsledky podobné.

**Comment by peci1** [comment]
Bohuzel, taky uz jsem par generatoru zkousel, vzdycky se spatnymi vysledky. Otazkou je, jestli by se Junak nemohl obratit na vyrobce fontu, zda by nam neposkytnul update. Treba ho maji a ani by to nebylo drahe. Ten font je obecne na dve veci, protoze treba PDF export z Libreoffice skonci s otazniky misto diakritiky. Takze ma urcite sve mouchy a ziskat jeho novou verzi by bylo vhodne :) Mate na ustredi nejaky kontakt?

**Comment by literat** [comment]
Předávám k řešení našemu grafikovi Ňufovi <nuf@skaut.cz>, ten se v tomhle ohledu dokáže vyjádřit asi lépe. I v tom ohledu, co by se dalo ještě vytáhnout. S ústředním jinak běžně spolupracujeme, takže kontakty jsou.

**Comment by davidurban** [comment]
Vím, že ten font není ideální, ale s tím my nic neuděláme. :) Je to na položení dotazu na ústředí, ale obecně si myslím, že v době prací na novém vizuálu tohle nikdo řešit nebude.
Já bych to teď tedy nechal být a řešil to v rámci nové vizuální identity – ta by měla být do půlky roku 2016, což není tak daleko…

**Comment by davidurban** [comment]
Navrhuju resolve > wontfix

**Comment by peci1** [comment]
Ok, kdyz si na to nekdo pri projednavani vzpomene, budu rad :) Pokud bude projednavani verejne, vzpomenu si sam =)

**Comment by peci1** [comment]
Ha, tak to, zda se, ma celkem jednoduche reseni.

Nasledujici vysledky jsou oba z FF na Windows (prvni je puvodni stav, druhy je opraveny font):

![clipboard01](https://cloud.githubusercontent.com/assets/182533/11615899/16165a7e-9c6d-11e5-9f18-a64893968891.jpg)

![clipboard02](https://cloud.githubusercontent.com/assets/182533/11615900/1865f578-9c6d-11e5-9654-981c2e6fdab7.jpg)

Opraveny font se da vygenerovat na https://fontie.flowyapps.com/home (je treba zaridit, aby mel vsechna ceska pismena - napr. zvolenim "keep existing" v kolonce "subsetting").

https://pixelsvsbytes.com/2013/11/how-to-create-perfect-web-fonts-in-3-steps/

Netestoval jsem to nijak dukladne, ale minimalne diakritiku v nadpisech to zvlada spravne.

**Comment by literat** [comment]
OK, vygeneroval jsem nový fotn přes fontie. Zkoušel jsem trochu ladit. Zdá se mi ok, nicméně prosím o potvrzení. Nově vygenerovaný font jsem zatím nasadil na http://dsw-piskoviste.skauting.cz/. Snad bude ok. Díkes.

**Comment by peci1** [comment]
Ne, to nasazene pismo se ukazuje stejne spatne jako to predchozi.

Davam k dispozici verzi, ktera funguje u me (a opravdu, velikost WOFF souboru se lisi oproti tomu nasazenemu na piskoviste).

https://app.box.com/s/ow2r53n66gc0jvfc8hc3k101ju6tu69p

Po opraveni bugu odkaz smazu.

**Comment by literat** [comment]
OK, díkes za odkaz ke stažení. Nahozeno na pískoviště. Předpokládám, že to bylo tím přepínačem Windows GDI. Vypadá již lépe.

**Comment by peci1** [comment]
Potvrzuju, na piskovisti uz je to v poradku.

**Comment by literat** [comment]
Připraveno do releasu další verze.
