### ISSUE TITLE
Pozicování pozadí

### ISSUE THREAD

**Issue by literat** [skaut/dsw-oddil#54]
Dořešit jednolitou barvu pozadí vs barvu pozadí článku/postu. Pravděpodobně bílý post a lehce šedé pozadí, aby byly jasné hranice.

**Comment by literat** [comment]
Na stránkách projektu jsem potkal výzvu k nahlášení chyb, tak píšu. Objevil jsem 2 chyby týkající se tý bílý věci se šmouhama na pozadí webu:
1)      Když je příspěvek delší, tak pozadí nedosahuje až dolů po ten proužek ale skončí dřív. Doufám že z obrázku 1 v příloze je to jasné.
2)      Když se hodně odzoomuje (jakože to nikdo nedělá, ale ať je šablona dokonalá), tak ta bílá věc zůstane nalevo a ne jako web uprostřed.

**Comment by davidurban** [comment]
1) i 2) máme nové pozadí, které je čistý gradient do bílé, takže by se to mělo řešit

**Comment by literat** [comment]
Považuji s další verzí za vyřešené. Přidáno pozadí pomocí gradientu. Myšleno u na starší prohlížeče. Drobné úpravy možné.
