### ISSUE TITLE
Omezení hloubky menu

### ISSUE THREAD

**Issue by vojta001** [skaut/dsw-oddil#57]
Proč omezujete hloubku menu? Možná to není obvyklé, ale na našem webu jsem musel hodnotu ručně zvednout, navíc je to takové poměrně "magic", když si pohrajete s menu a ono v něm z čista jasna chybí položky.

header.php:59
```php
$dswoddil_menu_data = wp_nav_menu( array(
	'echo'				=> false,
	'menu'              => 'primary',
	'theme_location'    => 'primary',
	'depth'             => 3,
	'container'         => 'div',
	'container_class'   => 'collapse navbar-collapse',
	'container_id'      => 'bs-example-navbar-collapse-1',
	'menu_class'        => 'nav navbar-nav',
	'fallback_cb'       => 'wp_bootstrap_navwalker::fallback',
	'walker'            => new wp_bootstrap_navwalker())
);
```
Je nějaký konkrétní důvod, proč hloubku omezovat?
Osobně bych nahradil podle [dokumentace](https://codex.wordpress.org/Function_Reference/wp_nav_menu):
```php
'depth'             => 3,
```
na
```php
'depth'             => 0,
```
nebo řádek úplně smazal.

**Comment by literat** [comment]
Upravil jsem menu, aby nebylo nikterak omezené. Tedy by nemělo nic bránit zanoření až do třeba 10. levelu. Nicméně menu, která se zanořují do větší hloubky než je 3 jsou z uživatelského hlediska velmi nepřehledná. Pokud je zanoření hlubší než třetí level, tak bych se spíš více zamyslel nad podobou menu a jeho obsahem, než nad nutností vkládat položky do nižších pater. Ze zkušenosti je tam návštěvník webu většinou nenajde.
