### ISSUE TITLE
odsazení Autora příspěvku

### ISSUE THREAD

**Issue by Clonewayx** [skaut/dsw-oddil#65]
Po aktualizaci na novou verzi šablony (0.14.0) a s tím spojeným přesunem odkazu na autora příspěvků se změnilo odsazení autora a textu a ten se teď nachází na řádku textu místo nad ním například:
http://tumulus.skauting.cz/lodi-proti-proudu-cezavy/
snímek:
![2015-11-17-090535_1680x1050_scrot](https://cloud.githubusercontent.com/assets/11831718/11205762/81052602-8d0a-11e5-98a2-57bd15c12d1d.png)

**Comment by literat** [comment]
V pravém horním rohu autor nemá být, je to nějaký relict po úpravě.

**Comment by literat** [comment]
Odebráno z entry-header.
