### ISSUE TITLE
Odkazy pod přízpěvky

### ISSUE THREAD

**Issue by Clonewayx** [skaut/dsw-oddil#66]
Pod příspěvky jsou odkazi na Předchozí a následující příspěvek ale v textu chybí mezery. Například: " Předchozí příspěvekVyšel WordPress 4.3.1Další příspěvekPlugin pro Bazary" http://dobryweb.skauting.cz/jak-se-nechat-informovat/
![2015-11-17-091145_1680x1050_scrot](https://cloud.githubusercontent.com/assets/11831718/11205883/8aa64dde-8d0b-11e5-8cd4-3a4337af0b45.png)

**Comment by literat** [comment]
Upraveno, zalomeno, přidáno odsazení.
