### ISSUE TITLE
Zvyseni bezpecnosti pomoci pluginu?

### ISSUE THREAD

**Issue by peci1** [skaut/dsw-oddil#69]
Ahoj, prislo by mi fajn, kdyby uz v zakladni instalaci byla vyssi mira zabezpeceni.

Napr. `Google Captcha (reCAPTCHA) by BestWebSoft` a `Limit Login Attempts` nebo neco podobneho. Ukradeny wordpress je totiz nocni murou kazdeho admina...

**Comment by literat** [comment]
Ahoj,
myslím si, že zrovna tohle je záležitostí administrátora webu a nemá se o to starat šablona.

V případě realizace automatické instalace Wordpressu na skautské weby tady ta možnost je. Avšak i zde je hodně diskutabilní, jestli a hlavně jaké pluginy použít. Ne každý je zrovna fanda reCaptchy či jiných řešení. Nehledě na to, že každý může preferovat jiný plugin nebo jiný stupeň zabezpečení.

Toto bych spíše řešil osvětovými články o tom, jak si svůj Wordpress zabezpečit a jaké pluginy jsou k tomu vhodné a jak se s nimi třeba pracuje.

**Comment by peci1** [comment]
Mozna by tedy mohl vznikat nejaky seznam doporucenych pluginu. Nejen z oblasti bezpecnosti, ale obecne - napadaji me treba kalendare (pokud nekomu nestaci iframe z Google kalendare).

**Comment by literat** [comment]
https://wordpress.org/plugins/better-wp-security/

Jeden z nejlepších pluginů ohledně bezpečnosti pro Wordpress.

Ohledně seznamu doporučovaných pluginů musí člověk spíše hledat a zkoušet.
https://www.google.cz/search?q=best+wordpress+plugin&ie=&oe=#q=wordpress+must+have+plugin
