### ISSUE TITLE
Zobrazení menu při šířce 770 - 980 px

### ISSUE THREAD

**Issue by Clonewayx** [skaut/dsw-oddil#70]
Při zobrazení s šírkou  mezi 770 a 980 pixely se celé menu rozbalí, a při větší složitosti se stává poměrně nepřehledným.

![screen shot 2016-01-25 at 12 09 54](https://cloud.githubusercontent.com/assets/11831718/12549289/9da48a4a-c35c-11e5-8203-2f45ddc18fde.png)
![screen shot 2016-01-25 at 12 09 37](https://cloud.githubusercontent.com/assets/11831718/12549290/9da6ea2e-c35c-11e5-8353-fd054d25e424.png)

**Comment by literat** [comment]
Upraveny responzivní breakpointy a opraveno menu. Aktualizováno tlačítko na otevírání menu v mobilní verzi pro lepší čitelnost.

**Comment by literat** [comment]
Textové řetězce ještě přeloženy. Půjde ven během týdne.
