### ISSUE TITLE
Obrazky organizaci v zahlavi (widgety) nerespektuji pouzite http/https schema.

### ISSUE THREAD

**Issue by peci1** [skaut/dsw-oddil#74]
Cesty k obrazkum nastavenym pres image widget maji schema ulozene natvrdo podle toho, jake bylo nastavene v admin rozhrani pri jejich vyberu.

To pak rozbije https verzi stranky, pokud nekdo obrazky zmenil v admin rozhrani pres http.

Viz napr. https://ctyrkazjh.martin-pecka.eu/ i http://ctyrkazjh.martin-pecka.eu/ : znak WOSM se nacita pres http, Junak pres https.

**Comment by literat** [comment]
Obrázky v záhlaví webu jsou vkládány pomocí widgetu a pluginu pro tento widget (Image widget). Ten si načítá url webu z nastavení (Nastavení -> Obecné: Instalace Wordpressu a Úvodní stránka webu) - zde musí být uvedeny obě URL s https://

Pokud je widget definován textově, tedy html, tak by mělo stačit nahradit http:// či https:// pouze dvěma lomítky, tedy //ctyrkazjh.martin-pecka.eu/. Zbylé už se doplňuje automaticky podle toho, jestli jsem přišel přes http nebo https.

Případně je možné vynutit používání https ještě přes .htaccess

**Comment by literat** [comment]
Pro Apache:
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{SERVER_PORT} 80
    RewriteRule ^(.*)$ https://www.yoursite.com/$1 [R,L]
</IfModule>
```
Pro Nginx:
```
server {
    listen 80;
    server_name yoursite.com www.yoursite.com;
    return 301 https://yoursite.com$request_uri;
}
```

**Comment by literat** [comment]
http://dobryweb.skauting.cz/jak-prejit-se-svym-dobrym-webem-na-https/

**Comment by peci1** [comment]
Hmm, a kdyz mam widget definovany v grafickem rozhrani? Tam nedostavam na vyber zadani URL obrazku...

**Comment by peci1** [comment]
A co mam delat s touhle chybou? 

Nahrávání smíšeného aktivního obsahu z „http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js?ver=1.11.3“ bylo zablokováno

**Comment by peci1** [comment]
+ jeden offtopic: nelze odkazovat na https://skaut.cz, jelikoz pouzity certifikat vyprsel uz predloni! Nemas nahodou kontakt na nekoho na Ustredi, kdo by s tim neco udelal?

**Comment by literat** [comment]
Začnu offtopicem: odkaz není obsah, takže můžeš odkazovat kam chceš a jak chceš, pokud ovšem odkazuješ ven ze svého webu, pak je jedno, jestli je daný web na http nebo https. Pokud odkazuješ v  rámci svého webu a jedeš na https, tak by si měl odkazovat https. Ale znovu opakuji, odkazem nedochází k načítání obsahu, ale přesměrování uživatele někam jinam.

**Comment by literat** [comment]
Ad Google Apis: to je moje chyba a je to v šabloně, během dnešního dne opravím a publikuji nový balíček.

**Comment by literat** [comment]
Co se pak týká widgetů, tak ty by měly pracovat s url, které jsou definovány v administraci Nastavení > Obecné > url webu a url hlavní stránky. Tedy pokud tam máš nastavené https, tak i obrázky by měly brát přes https. Druhá možnost je, že to ten widget nebere v potaz a pak je špatně naimplementován.

**Comment by peci1** [comment]
Diky za odpovedi. Koukam, ze jsem to v puvodnim bugreportu nepopsal dostatecne. URL tech obrazku zavisi na tom, jestli jsem k admin rozhrani pristoupil pres http nebo https. Takze s nastavenim url webu to neni spojene. Je na to pouzit klasicky image widget ze sablony.

**Comment by literat** [comment]
Jestli si četl článek výše, tak tam je to popsané. Musíš přistupovat jednotně všude. Tedy pro admin je to ta definice `define('FORCE_SSL_ADMIN', true);`, kterou musíš dát do wp-config.php a pak bude administrace vynucovat https. On je WordPress i docela chytrý. Pokud přistupuješ přes http, tak se ti snaží vše servírovat přes http, pokud přes https, tak pokud bude moci, tak ti to naservíruje přes https. Ale to, o co se snažíme, je, aby servíroval vše přes https. Proto je tam i ten redirect v .htaccess.

**Comment by literat** [comment]
Vypuštěna oprava v0.16.1.
