### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by kalich5** [skaut/dsw-oddil#76]
The design is messed up. Click here to see how the theme looks on my desktop. Please fix this. https://dl.dropboxusercontent.com/u/22885614/dsw-oddill-101.jpg

**Comment by literat** [comment]
Jo, odstranil jsem widgety v hlavičce, nač si komplikovat život.

**Comment by kalich5** [comment]
Až bude šablona venku, tak se na to znova můžeme podívat. A zas to tam přidat.

**Comment by literat** [comment]
Upraveno, co šlo.
