### ISSUE TITLE
 licenses

### ISSUE THREAD

**Issue by kalich5** [skaut/dsw-oddil#81]
Declare licenses of any resources included such as fonts or images. You need to declare licenses for everything that your theme uses: fonts, images, code.

**Comment by literat** [comment]
Potřebuju zjistit, bod jakou licensí je poskytován font The Mix CE, který pozužíváme.

**Comment by literat** [comment]
Kalich: K tomu co je naše, bych dal licenci GPL2 a máme klid.

**Comment by literat** [comment]
Hele, co s tím písmem The Mix CE? Není svobodné, Junák ho zakoupil pro svoje potřeby a rozhodně si nemyslím, že máme právo ho distribuovat pod nějakou otevřenou licencí...

**Comment by kalich5** [comment]
Hmm, to asi nemáme no. Tak to musíme vyměnit za nějaký podobný font. Není něco mezi Google fonts?

**Comment by literat** [comment]
Nestudoval jsem, tohle myslím řešil hlavně Ňuf. Každopádně něco z Google fontů by bylo asi lepší, no.

**Comment by kalich5** [comment]
Jako změnu podle mě udělat musíme. Vzhled musí být pod stejnou licencí jako WP, tedy pod GPL2 a pod takovou licencí podle mě nebude. Osobně bych to změnil. A třeba časem zjistil, jestli to půjde použít.

**Comment by literat** [comment]
Použít PtSans - https://www.google.com/fonts/specimen/PT+Sans

**Comment by vojta001** [comment]
Font pod otevřenou licencí být nemusí, viz [vyjádření Software Freedom Law Center](https://wordpress.org/news/2009/07/themes-are-gpl-too)
