### ISSUE TITLE
Theme URL

### ISSUE THREAD

**Issue by kalich5** [skaut/dsw-oddil#84]
Theme URI is optional. If used, it is required to link to a page with information about the Theme. The link you provided presents information about a lot of themes.

**Comment by kalich5** [comment]
Můžeme ho používat, tak já udělám na stránkách přímo stránku kde můžeme napsat informace k tomu tématu. A stejně bych to udělal i u toho nového co bude inspirované novým vizuálním stylem.

**Comment by literat** [comment]
Pro jednoduchost bych momentálně odebral. Je to rychlejší řešení, než kvůli tomu zakládat web. Na to si uděláme nějaký jiný úkol. Respektive takovým webem by asi měl být dsw-oddil.skauting.cz, což moentálně není.
