### ISSUE TITLE
Required to use core-bundled scripts rather than including their own version of that script. For example jQuery.

### ISSUE THREAD

**Issue by kalich5** [skaut/dsw-oddil#97]
Code like functions.php, lines 141-149 is not allowed.

**Comment by literat** [comment]
Viz https://developer.wordpress.org/reference/functions/wp_enqueue_script/ a část Default Scripts Included and Registered by WordPress

**Comment by janzarsky** [comment]
Používá se core-bundled jQuery, žádný další ze skriptů není k dispozici ve WordPressu
